version: 1.0.{build}

os:
  - Visual Studio 2015

configuration:
- Debug
- Release

install:
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha7/premake-5.0.0-alpha7-windows.zip' 'premake.zip'

  - 7z x premake.zip

  - premake5.exe vs2015

build:
  project: ./build/lisianthus.sln
