version: 1.0.{build}
os: Visual Studio 2015
configuration:
- Debug
- Release
platform: x64
install:
  # Download Premake
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha7/premake-5.0.0-alpha7-windows.zip' 'premake.zip'

  # Extract it in-place; premake5.exe is at the top level.
  - 7z x premake.zip

  - cmd premake5.exe vs2015

build:
  project: build/lisianthus.sln
